import type { Metadata } from "next";
import { Source_Code_Pro, Noto_Sans_KR } from "next/font/google";
import "../globals.css";
import ThemeProvider from "../_component/ThemeProvider";
import Header from "../_component/Header";
import ProfileCard from "../_component/ProfileCard";
import TopTabs from "../_component/Toptabs";

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sourcecodepro",
});

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-noto-sans-kr",
});

export const metadata: Metadata = {
  title: "bienew's blog",
  description: "Generated by @BieNew22",
};

export default function ShellLayout({children, }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${sourceCodePro.variable} ${notoSansKr.variable} antialiased`}
      >
        <ThemeProvider>
          <Header />
          <main className="mx-auto max-w-5xl px-4">
            <ProfileCard />
              <TopTabs />
            <section className="py-8">{children}</section>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}