import "./globals.css";
import { Source_Code_Pro, Noto_Sans_KR } from "next/font/google";
import type { Metadata } from "next";
import ThemeProvider from "@/component/ThemeProvider";

export const metadata: Metadata = {
  title: "bienew's blog",
  description: "Generated by @BieNew22",
};

const sourceCodePro = Source_Code_Pro({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sourcecodepro",
});

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-noto-sans-kr",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${sourceCodePro.variable} ${notoSansKr.variable} antialiased`}
      >
        <ThemeProvider>
            {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
